[book]
authors = ["cyberyzy"]
language = "zh-CN"
multilingual = false
src = "src"
title = "电力系统学习指导"

[output.html]
mathjax-support = true

[preprocessor.katex]

after = ["links"]
# KaTeX options.
output = "mathml"
